# This is the schema for the Shell Adventure config file. It is used by [Yamale](https://pypi.org/project/yamale) to validate the config file.
image: str(required = False)
home: str(required = False)
user: str(required = False)
modules: list(str())
puzzles: list(include('puzzle'), min = 1)
setup_scripts: list(str(), required = False)
resources: map(str(), key = str(), required = False)
name_dictionary: str(required = False)
content_sources: list(str(), required = False)
restart_enabled: bool(required = False)

--- # Includes
puzzle_identifier: regex(r"^[^\d\W]\w*\.[^\d\W]\w*$", name = "python identifier of format 'module.puzzle'")
# To make a pretty tree structure, puzzle is a str or single element dict containing a list of puzzles
puzzle: any(include('puzzle_identifier'), map(list(include('puzzle'), required = False), key = include('puzzle_identifier'), min = 1, max = 1))
